const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.EXECUTAR_PLAYWRIGHT_MODULE||'playwright');const c=(process.env.EXECUTAR_CHROMIUM_MODULE?require(process.env.EXECUTAR_CHROMIUM_MODULE):{args:[]});
const root=path.join(__dirname,'..'),config=JSON.parse(fs.readFileSync(root+'/vercel.json'));
const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname,r=config.routes.find(r=>new RegExp('^'+r.src+'$').test(p));if(!r){res.writeHead(404);return res.end()}const dest=p.replace(new RegExp('^'+r.src+'$'),r.dest);res.setHeader('Content-Type',dest.endsWith('.mjs')?'text/javascript':dest.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,dest)))});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({executablePath:process.env.EXECUTAR_BROWSER_PATH,args:c.args,headless:true});const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('executar-scroll-v7')));const load=async route=>{await page.goto(url+route);await page.waitForSelector('.taskRow,.focusSlide,#settings:not([hidden])');await page.waitForTimeout(200)};
await load('/tarefas');assert.equal(await page.locator('.taskRow').count(),30);await page.screenshot({path:'/tmp/executar-list-desktop.png'});await page.locator('[data-check="0"]').check();assert.deepEqual((await state()).done,['t1']);await page.locator('[data-detail="1"]').first().click();await page.locator('#taskNote').fill('Nota preservada');await page.locator('#closeTask').click();await page.locator('#viewToggle').click();await page.waitForTimeout(300);assert.equal((await state()).view,'scroll');assert.equal((await state()).index,1);assert.equal((await state()).notes.t2,'Nota preservada');await page.locator('#nextUnit').click();await page.waitForTimeout(300);assert.equal((await state()).index,2);assert.deepEqual((await state()).done,['t1']);await page.goBack();await page.waitForTimeout(300);assert.equal((await state()).index,1);
await load('/tarefas');const box=await page.locator('#scroller').boundingBox();await page.mouse.move(box.x+120,box.y+100);await page.mouse.wheel(0,600);await page.waitForTimeout(300);assert.deepEqual((await state()).done,['t1']);await load('/foco?unidade=t3');await page.waitForTimeout(1000);const f=await page.locator('#scroller').boundingBox();await page.mouse.move(f.x+120,f.y+120);await page.mouse.wheel(0,f.height);await page.waitForTimeout(600);assert((await state()).done.includes('t3'));
await load('/configuracoes');await page.locator('#theme').selectOption('dark');await page.locator('#completeOnScroll').uncheck();await page.reload();await page.waitForTimeout(300);assert.equal((await state()).theme,'dark');assert.equal((await state()).scrollCompletes,false);
await page.locator('#theme').selectOption('system');
await load('/foco?unidade=t1');const beforeAuto=(await state()).done;await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('executar-scroll-v7'));s.remaining=.2;s.auto=true;localStorage.setItem('executar-scroll-v7',JSON.stringify(s))});await page.reload();await page.locator('#timerToggle').click();await page.waitForTimeout(700);assert.equal((await state()).index,1);assert.deepEqual((await state()).done,beforeAuto);await page.locator('#timerToggle').click();
await load('/tarefas');await page.locator('#more').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#more').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.deepEqual((await state()).done,beforeAuto);

for(const [width,height,scale] of [[390,844,1],[320,568,1],[844,390,1],[390,844,2]]){await page.setViewportSize({width,height});await load('/tarefas');await page.evaluate(scale=>document.documentElement.style.fontSize=16*scale+'px',scale);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}/${scale}`);if(width===390&&scale===1){await page.screenshot({path:'/tmp/executar-list-mobile.png'});await page.locator('#openNavigation').click();await page.screenshot({path:'/tmp/executar-navigation-mobile.png'});await page.locator('#closeNavigation').click();await page.locator('[data-detail="0"]').first().click();await page.screenshot({path:'/tmp/executar-details-mobile.png'});await page.locator('#closeTask').click()}}
await page.setViewportSize({width:390,height:844});await load('/configuracoes');await page.screenshot({path:'/tmp/executar-settings-mobile.png'});await page.emulateMedia({colorScheme:'dark',contrast:'more'});await load('/tarefas');await page.screenshot({path:'/tmp/executar-list-dark.png'});await page.evaluate(()=>document.documentElement.dir='rtl');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS: browser list, checkbox, notes, mode switch, route/back, list scroll exclusion, manual focus completion, settings persistence, desktop/mobile/landscape/200% text, dark and contrast; no JS errors.');await browser.close();server.close()})().catch(e=>{console.error(e);server.close();process.exit(1)});
